version: '3.8'

services:
  web:
    build:
      context: .
    command: gunicorn --workers=3 --bind=0.0.0.0:8080 UDL_project.wsgi:application
    volumes:
      - .:/app
    ports:
      - "8080:8080"
    env_file:
      - UDL_project/.env
    environment:
      - PORT=8080
