version: '3.8'

services:
  web:
    build:
      context: .
    command: gunicorn --workers=3 --bind=0.0.0.0:8080 UDL_project.wsgi:application
    volumes:
      - .:/app
    ports:
      - "8080:8080"
    environment:
      - SECRET_KEY=${SECRET_KEY}
      - DEBUG=${DEBUG}
      - ALLOWED_HOSTS=${ALLOWED_HOSTS}
      - DATABASE_URL=${DATABASE_URL}
      - PORT=8080 
    # OR:
    # env_file:
    #   - .env