version: '3.8'

services:
  web:
    build:
      context: .
    command: gunicorn UDL_project.wsgi
    volumes:
      - .:/app
    # ports:
    #   - "8000:8000"
    env_file:
      - UDL_project/.env
    # environment:
    #   - PORT=8000
