version: '3.8'

services:
  web:
    build:
      context: .
    command: daphne -b 0.0.0.0 -p 10000 UDL_project.asgi:application
  # command: gunicorn --workers=3 --bind=0.0.0.0:10000 UDL_project.wsgi:application
    volumes:
      - .:/app
    ports:
      - "10000:10000"
    env_file:
      - UDL_project/.env
    environment:
      - PORT=10000
