"""
Django settings for UDL_project project.

Generated by 'django-admin startproject' using Django 5.0.4.

For more information on this file, see
https://docs.djangoproject.com/en/5.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.0/ref/settings/
"""
import environ
import dj_database_url
import os
from pathlib import Path


# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Take environment variables from .env file
# environ.Env.read_env(os.path.join(BASE_DIR, '.env'))
env = environ.Env()
environ.Env.read_env()


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!

SECRET_KEY = env('SECRET_KEY')

# SECURITY WARNING: don't run with debug turned on in production!
# False if not in os.environ because of casting above
# DEBUG = env('DEBUG')
DEBUG = False

ALLOWED_HOSTS = env.list('ALLOWED_HOSTS', default=['*'])

# ALLOWED_HOSTS = ['localhost', '127.0.0.1', 'udl.onrender.com']


# Application definition

INSTALLED_APPS = [
    'jet.dashboard',
    'jet',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    "crispy_forms",
    "crispy_bootstrap5",
    'channels',
    'udl_app',
    'accounts',
    'sass_processor',
    'embed_video',
    'ckeditor',
]

ASGI_APPLICATION = 'UDL_project.asgi.application'
CHANNEL_LAYERS = {
    'default': {
        'BACKEND': 'channels_redis.core.RedisChannelLayer',
        'CONFIG': {
            "hosts": [('127.0.0.1', 6379)],
        },
    },
}

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django_session_timeout.middleware.SessionTimeoutMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'UDL_project.customMiddleWare.AdminAccessMiddleware',
    'UDL_project.customMiddleWare.AllowIframeFrom',
    'UDL_project.customMiddleWare.OneSessionPerUserMiddleware',
]

ROOT_URLCONF = 'UDL_project.urls'
AUTH_USER_MODEL='udl_app.BaseUser'

# X_FRAME_OPTIONS = 'SAMEORIGIN'

LOGIN_REDIRECT_URL = "/"
LOGOUT_REDIRECT_URL = "/" 

CRISPY_ALLOWED_TEMPLATE_PACKS = "bootstrap5"
CRISPY_TEMPLATE_PACK = "bootstrap5"

SESSION_EXPIRE_SECONDS = 600
SESSION_EXPIRE_AFTER_LAST_ACTIVITY = True
# SESSION_EXPIRE_AFTER_LAST_ACTIVITY_GRACE_PERIOD = 60
SESSION_TIMEOUT_REDIRECT = 'dashboard'
SESSION_EXPIRE_AT_BROWSER_CLOSE=True
# settings.py
JWT_PRIVATE_KEY = '''-----BEGIN PRIVATE KEY-----
MIIEvgIBADANBgkqhkiG9w0BAQEFAASCBKgwggSkAgEAAoIBAQCM8O1Hubk+rib3
bbZxXbsiNK4cp0ryWloP24MyHATd8H9f2BglhHRKNbwlXkjtmdDwRtAACgT/smJ0
UeUX8BOy+gg2mmifVhTCEm1kw5B69YwsXtw9nVrZQ8/vdf7VQ3k6Mj3FiosUWk0L
ot110O0htOsyUrcippDhKT79GFl6HiALG5usSdRaj2X5Elgn+VCzpvSs4IjUZA+M
lR9IIsMKYRbr0gBPerrkVjdqw2fZoMyDUqR/jT7r7iOrMIRlyG+FDxbGZzh711ej
e7WJzF//Z4Odovo721JjuK/TiP/87n9dBz/zFYy+la5j9hG2zjcEAY2aSx5gejJ/
RucuB3bLAgMBAAECggEACN79QF97Pmu9viMksZwBtFR2hQ0ulXSEaK0bY+MJl2KU
0daLJolgvG8HaZ62nmXpFcaPPwFicSmsMsAY2FnfE4vTSoSLg0PqyJBaXFZG2MZt
zTknSaWG21f+VYcqxAecMMKKys0+lchdQxc8Mzc0RcPabe9w4Xh0dAehlFKdByeY
P0L1IOztsMC0jODGt94jbjU/ItH2DlKhcOlG4+A/A/JYvRlkkIZ7PQnGriBiovjF
QjvwL7+UV2Lugsc1sPPrZG+hR9RjyXjXkMUUgJojhm0eViv8p3qYksrU3XTzUD+q
RUOKpvor1hugoXv9iOcxOh/smjRfRySO5KqKBEuviQKBgQDQS+rOlC4diXIcU7j2
t1betGv70P4jmoazkMjH6c4KZnBGNts3Wra/J4ll/Cf+PnJBICuPLV8Q5r8bxpYL
ufu9RlvC1U8Gf8youJYLbITX715hSTXi1LilHQWm+QxE87YwrKANaNWVBhyRUB09
y1raDx9zUTzCKJg1XNmK+fjBXQKBgQCtOBJt5oSutOoRoYsN3c7cuEDI0eL2LpbP
oYR8yBLhtmmK7FBb+5bhRHayCRJlvHur6CLmLKXzf8xsQ1NCO93NtziHDRqzk15W
sQQ+Vbb8BNMn9ZPT+eSs0VFPdeX/6TKwkCSsdPlasJ/q7PVf331oqpZX9zMh2W/L
iL0A7CXORwKBgQC/R6gWEn+SwkBXAQ9PCSguFXNAaTioS2Q9i8zFwNBkPpQF9qQy
3gwJ2G3ViMzVLlVPtxIpRloRtER1ZlUt6Zniw7TKY4ZRipTPr8qiLQKFJZz/K/Lf
Hcd+YPtqzTPWMhPx+OR1y/qvAlDDpNVlhNQmgVK5XDW2ev7jqiNf+5PTRQKBgQCT
DB3BBEcw1M48B2o3bEvW3efJUzwcBzLpslD5aRN2X1c7ox8Y5vyP4YHt43uluBs4
tUkjI1YB30TXx1Ofz5icsWSgaUR4m6sjZwSWMkezrBjhPD2xXtt8xfkDvq9wzzPD
5ansaSThkz0+vsgTCnO47c/Rfz3+B0s7eqoQZWg2swKBgECGJZELaiZcJ/XQqsTp
UT4H2pNL4MiMG9G/HmnNOAYJEq7+Y1RtA2LoW26ZiuQS+Xqnq++U83lq9+B6saHl
DxpOkphywD0BQGBj7odiefXjVjqzjMZEL3cEkJj/crhfXPVWDneXNp3C6hgbHY0d
HoKqJ25TSKH9Q1DBFNzkjl7p
-----END PRIVATE KEY-----
'''
JWT_PUBLIC_KEY='''-----BEGIN PUBLIC KEY-----
MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAjPDtR7m5Pq4m9222cV27
IjSuHKdK8lpaD9uDMhwE3fB/X9gYJYR0SjW8JV5I7ZnQ8EbQAAoE/7JidFHlF/AT
svoINppon1YUwhJtZMOQevWMLF7cPZ1a2UPP73X+1UN5OjI9xYqLFFpNC6LdddDt
IbTrMlK3IqaQ4Sk+/RhZeh4gCxubrEnUWo9l+RJYJ/lQs6b0rOCI1GQPjJUfSCLD
CmEW69IAT3q65FY3asNn2aDMg1Kkf40+6+4jqzCEZchvhQ8Wxmc4e9dXo3u1icxf
/2eDnaL6O9tSY7iv04j//O5/XQc/8xWMvpWuY/YRts43BAGNmkseYHoyf0bnLgd2
ywIDAQAB
-----END PUBLIC KEY-----
'''

JITS_FEATURES = {
    # 'livestreaming': 'false',
    # 'recording': 'false',
    # 'transcription': 'false',
    # 'sip-inbound-call': 'false',
    # 'sip-outbound-call': 'false',
    # 'inbound-call': 'false',
    # 'outbound-call': 'false'
    "livestreaming": True,
    "outbound-call": True,
    "sip-outbound-call": False,
    "transcription": True,
    "recording": True
}


TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'UDL_project.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.0/ref/settings/#databases

DATABASES = {
    # 'default': {
    #     'ENGINE': 'django.db.backends.postgresql',
    #     'NAME': env('DB_NAME'),
    #     'USER': env('DB_USER'),
    #     'PASSWORD': env('DB_PSW'),
    #     # 'HOST': env('DB_HOST'),
    #     'HOST': 'db',
    #     'PORT': env('DB_PORT'),
    # }

        'default': dj_database_url.parse(env('DATABASE_URL'))
  
}


# Password validation
# https://docs.djangoproject.com/en/5.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]
PASSWORD_HASHERS = [
    "django.contrib.auth.hashers.Argon2PasswordHasher",
    "django.contrib.auth.hashers.PBKDF2PasswordHasher",
    "django.contrib.auth.hashers.PBKDF2SHA1PasswordHasher",
    "django.contrib.auth.hashers.BCryptSHA256PasswordHasher",
    "django.contrib.auth.hashers.ScryptPasswordHasher",
]

# Internationalization
# https://docs.djangoproject.com/en/5.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Africa/Mogadishu'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.0/howto/static-files/

STATIC_URL = 'static/'
STATICFILES_DIRS = [os.path.join(BASE_DIR, 'static')]
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')

SASS_PROCESSOR_ROOT = os.path.join(BASE_DIR, 'static')


STATICFILES_FINDERS = [
    'django.contrib.staticfiles.finders.FileSystemFinder',
    'django.contrib.staticfiles.finders.AppDirectoriesFinder',
    'sass_processor.finders.CssFinder',
]

# Media files config
MEDIA_URL = "/media/"
MEDIA_ROOT = os.path.join(BASE_DIR, "media")

STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage' 

# Default primary key field type
# https://docs.djangoproject.com/en/5.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


# settings.py
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'handlers': {
        'file': {
            'level': 'DEBUG',
            'class': 'logging.FileHandler',
            'filename': os.path.join(BASE_DIR, 'debug.log'),
        },
    },
    'loggers': {
        'django': {
            'handlers': ['file'],
            'level': 'DEBUG',
            'propagate': True,
        },
    },
}


EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_HOST_USER = 'madard.edu@gmail.com'
EMAIL_HOST_PASSWORD = 'uusg shlt bxki dmll'

