# Generated by Django 5.0.4 on 2024-07-06 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('udl_app', '0002_question_course_alter_profile_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='telephone',
            field=models.CharField(blank=True, max_length=15),
        ),
    ]
