# Generated by Django 5.0.4 on 2024-07-06 10:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('udl_app', '0003_profile_telephone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='enrolledcourse',
            name='course',
        ),
        migrations.AlterField(
            model_name='enrolledcourse',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrolled_student', to='udl_app.student'),
        ),
        migrations.AddField(
            model_name='enrolledcourse',
            name='course',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='enrolled_course', to='udl_app.course'),
            preserve_default=False,
        ),
    ]
