# Generated by Django 5.0.4 on 2024-07-06 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('udl_app', '0004_remove_enrolledcourse_course_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='image',
            field=models.ImageField(blank=True, default='course_images/University_of_Hargeisa.svg', null=True, upload_to='course_images/'),
        ),
    ]
