# Generated by Django 5.0.4 on 2024-07-06 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('udl_app', '0005_course_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='image',
            field=models.ImageField(blank=True, default='course_images/University_of_Hargeisa1.svg', null=True, upload_to='course_images/'),
        ),
    ]
