# Generated by Django 5.0.4 on 2024-07-06 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('udl_app', '0006_alter_course_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='image',
            field=models.ImageField(blank=True, default='course_images/uoh.jpg', null=True, upload_to='course_images/'),
        ),
    ]
