# Generated by Django 5.0.4 on 2024-07-07 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('udl_app', '0007_alter_course_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='baseuser',
            name='is_admin',
            field=models.BooleanField(default=False),
        ),
    ]
