# Generated by Django 5.0.4 on 2024-07-07 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('udl_app', '0008_baseuser_is_admin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lecture',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
