# Generated by Django 5.0.4 on 2024-07-07 08:58

import embed_video.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('udl_app', '0009_alter_lecture_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lecture',
            name='video_url',
            field=embed_video.fields.EmbedVideoField(blank=True, null=True),
        ),
    ]
