# Generated by Django 5.0.4 on 2024-07-07 09:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('udl_app', '0010_alter_lecture_video_url'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lecture',
            old_name='video_url',
            new_name='video',
        ),
    ]
