# Generated by Django 5.0.4 on 2024-07-08 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('udl_app', '0011_rename_video_url_lecture_video'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resource',
            name='course',
        ),
        migrations.AddField(
            model_name='resource',
            name='lecture',
            field=models.ManyToManyField(blank=True, related_name='resources', to='udl_app.lecture'),
        ),
    ]
