# Generated by Django 5.0.4 on 2024-07-09 05:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('udl_app', '0012_remove_resource_course_resource_lecture'),
    ]

    operations = [
        migrations.CreateModel(
            name='LectureProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completed', models.BooleanField(default=False)),
                ('lecture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='udl_app.lecture')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='udl_app.student')),
            ],
        ),
    ]
