# Generated by Django 5.0.4 on 2024-07-09 14:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('udl_app', '0014_semester_school_semesters'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='semester',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='udl_app.semester'),
            preserve_default=False,
        ),
    ]
