# Generated by Django 5.0.4 on 2024-07-09 18:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('udl_app', '0015_course_semester'),
    ]

    operations = [
        migrations.RenameField(
            model_name='assignmentgrade',
            old_name='assignment',
            new_name='assignment_solution',
        ),
    ]
