# Generated by Django 5.0.4 on 2024-07-10 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('udl_app', '0016_rename_assignment_assignmentgrade_assignment_solution'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='exam_type',
            field=models.CharField(choices=[('Midterm', 'Midterm'), ('Final', 'Final')], default='Midterm', max_length=10),
        ),
    ]
