# Generated by Django 5.0.4 on 2024-07-10 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('udl_app', '0019_rename_text1_choice_choice1_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='choice',
            old_name='choice1',
            new_name='choice',
        ),
        migrations.RemoveField(
            model_name='choice',
            name='choice2',
        ),
        migrations.RemoveField(
            model_name='choice',
            name='choice3',
        ),
        migrations.RemoveField(
            model_name='choice',
            name='choice4',
        ),
        migrations.AddField(
            model_name='question',
            name='marks',
            field=models.FloatField(default=1),
        ),
        migrations.AlterField(
            model_name='choice',
            name='correct_choice',
            field=models.CharField(default='choice1', max_length=7),
        ),
    ]
