# Generated by Django 5.0.4 on 2024-07-12 08:43

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('udl_app', '0021_alter_choice_correct_choice'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quizsubmission',
            name='quiz',
        ),
        migrations.RemoveField(
            model_name='quizgrading',
            name='grade_ptr',
        ),
        migrations.RemoveField(
            model_name='quizgrading',
            name='submission',
        ),
        migrations.RemoveField(
            model_name='quizsubmission',
            name='student',
        ),
        migrations.RemoveField(
            model_name='message',
            name='recipient',
        ),
        migrations.AddField(
            model_name='message',
            name='recipients',
            field=models.ManyToManyField(related_name='received_messages', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='exam',
            name='exam_type',
            field=models.CharField(choices=[('Midterm', 'Midterm'), ('Final', 'Final'), ('Quiz', 'Quiz')], default='Midterm', max_length=10),
        ),
        migrations.DeleteModel(
            name='Quiz',
        ),
        migrations.DeleteModel(
            name='QuizGrading',
        ),
        migrations.DeleteModel(
            name='QuizSubmission',
        ),
    ]
