# Generated by Django 5.0.4 on 2024-07-22 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('udl_app', '0023_message_is_read'),
    ]

    operations = [
        migrations.RenameField(
            model_name='discussion',
            old_name='message',
            new_name='content',
        ),
        migrations.AlterField(
            model_name='semester',
            name='semester',
            field=models.IntegerField(choices=[(1, 1), (2, 2)], default=1),
        ),
    ]
