# Generated by Django 5.0.4 on 2024-07-25 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('udl_app', '0026_alter_question_question'),
    ]

    operations = [
        migrations.AddField(
            model_name='baseuser',
            name='current_session_key',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
