# Generated by Django 5.0.4 on 2024-07-25 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('udl_app', '0027_baseuser_current_session_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lecture',
            name='video',
            field=models.CharField(blank=True, null=True),
        ),
    ]
