# Generated by Django 5.0.4 on 2024-07-27 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('udl_app', '0029_alter_lecture_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='lecture',
            name='answer',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='lecture',
            name='question',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
