# Generated by Django 5.0.4 on 2024-07-27 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('udl_app', '0030_lecture_answer_lecture_question'),
    ]

    operations = [
        migrations.AddField(
            model_name='lecture',
            name='time',
            field=models.FloatField(blank=True, default=0, help_text='Time in minutes', null=True),
        ),
    ]
