# Generated by Django 5.0.4 on 2024-07-27 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('udl_app', '0032_alter_lecture_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lecture',
            name='answer',
        ),
        migrations.RemoveField(
            model_name='lecture',
            name='question',
        ),
        migrations.RemoveField(
            model_name='lecture',
            name='time',
        ),
        migrations.CreateModel(
            name='LectureQuestions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=255)),
                ('answer', models.CharField(max_length=255)),
                ('time', models.FloatField(blank=True, default=0, help_text='Time in minutes eg. 1.5, 2, 2.1, 3.9', null=True)),
                ('lecture', models.ManyToManyField(related_name='lecture_questions', to='udl_app.lecture')),
            ],
        ),
    ]
