# Generated by Django 5.0.4 on 2024-07-27 11:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('udl_app', '0033_remove_lecture_answer_remove_lecture_question_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lecturequestions',
            name='lecture',
        ),
        migrations.AddField(
            model_name='lecturequestions',
            name='lecture',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='lecture_questions', to='udl_app.lecture'),
            preserve_default=False,
        ),
    ]
